export const MANUFACTURING_ORDER_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
};

export const MANUFACTURING_ORDER_STATUS_COLORS = {
  [MANUFACTURING_ORDER_STATUS.PENDING]: 'blue',
  [MANUFACTURING_ORDER_STATUS.APPROVED]: 'green',
  [MANUFACTURING_ORDER_STATUS.IN_PROGRESS]: 'cyan',
  [MANUFACTURING_ORDER_STATUS.COMPLETED]: 'lime',
  [MANUFACTURING_ORDER_STATUS.CANCELLED]: 'red',
};

export const MANUFACTURING_ORDER_STATUS_LABELS = {
  [MANUFACTURING_ORDER_STATUS.PENDING]: 'Chờ thực hiện',
  [MANUFACTURING_ORDER_STATUS.APPROVED]: 'Đã phê duyệt',
  [MANUFACTURING_ORDER_STATUS.IN_PROGRESS]: 'Đang thực hiện',
  [MANUFACTURING_ORDER_STATUS.COMPLETED]: 'Hoàn thành',
  [MANUFACTURING_ORDER_STATUS.CANCELLED]: 'Đã hủy',
};

export const MANUFACTURING_ORDER_STATUS_OPTIONS = [
  { value: '', label: 'Tất cả trạng thái' },
  { value: MANUFACTURING_ORDER_STATUS.PENDING, label: MANUFACTURING_ORDER_STATUS_LABELS.PENDING },
  { value: MANUFACTURING_ORDER_STATUS.APPROVED, label: MANUFACTURING_ORDER_STATUS_LABELS.APPROVED },
  { value: MANUFACTURING_ORDER_STATUS.IN_PROGRESS, label: MANUFACTURING_ORDER_STATUS_LABELS.IN_PROGRESS },
  { value: MANUFACTURING_ORDER_STATUS.COMPLETED, label: MANUFACTURING_ORDER_STATUS_LABELS.COMPLETED },
  { value: MANUFACTURING_ORDER_STATUS.CANCELLED, label: MANUFACTURING_ORDER_STATUS_LABELS.CANCELLED },
];
